var vanillaBiomes = [
    "Badlands",
    "Bamboo Jungle",
    "Beach",
    "Brich Forest",
    "Cold Ocean",
    "Dark Forest",
    "Deep Cold Ocean",
    "Deep Frozen Ocean",
    "Deep Lukewarm Ocean",
    "Deep Ocean",
    "Desert",
    "Eroded Badlands",
    "Flower Forest",
    "Forest",
    "Frozen Ocean",
    "Frozen Peaks",
    "Frozen River",
    "Grove",
    "Ice Spikes",
    "Jagged Peaks",
    "Jungle",
    "Lukewarn Ocean",
    "Mangrove Swamp",
    "Meadow",
    "Mushroom Fields",
    "Ocean",
    "Old Growth Birch Forest",
    "Old Growth Pine Taiga",
    "Old Growth Spruce Taiga",
    "Plains",
    "River",
    "Savanna Plateau",
    "Snowy Beach",
    "Snowy Plains",
    "Snowy Slopes",
    "Snowy Taiga",
    "Sparce Jungle",
    "Stony Peaks",
    "Stony Shore",
    "Sunflower Plains",
    "Swamp",
    "Taiga",
    "Warm Ocean",
    "Windswept Forest",
    "Windswept Gravelly Hills",
    "Windswept Hills",
    "Windswept Savanna",
    "Wooded Badlands"
];

var terralithBiomes = [
    "Alpha Islands",
    "Alpha Islands Winter",
    "Alpine Grove",
    "Alpine Highlands",
    "Amethyst Canyon",
    "Amethyst Rainforest",
    "Ancient Sands",
    "Arid Highlands",
    "Ashen Savanna",
    "Basalt Cliffs",
    "Birch Taiga",
    "Blooming Plateau",
    "Blooming Valley",
    "Brushland",
    "Bryce Canyon",
    "Caldera",
    "Cloud Forest",
    "Cold Shrubland",
    "Desert Canyon",
    "Desert Oasis",
    "Desert Spires",
    "Emerald Peaks",
    "Forested Highlands",
    "Fractured Savanna",
    "Frozen Cliffs",
    "Glacial Chasm",
    "Granite Cliffs",
    "Gravel Beach",
    "Gravel Desert",
    "Haze Mountain",
    "Highlands",
    "Hot Shrubland",
    "Ice Marsh",
    "Jungle Mountains",
    "Lavender Forest",
    "Lavender Valley",
    "Lush Desert",
    "Lush Valley",
    "Mirage Isles",
    "Moonlight Grove",
    "Moonlight Valley",
    "Mountain Steppe",
    "Orchid Swamp",
    "Painted Mountains",
    "Red Oasis",
    "Rocky Jungle",
    "Rocky Mountains",
    "Rocky Shrubland",
    "Sakura Grove",
    "Sakura Valley",
    "Sandstone Valley",
    "Savanna Badlands",
    "Savanna Slopes",
    "Scarlet Mountains",
    "Shield",
    "Shield Clearing",
    "Shrubland",
    "Siberian Grove",
    "Siberian Taiga",
    "Skylands",
    "Skylands Autumn",
    "Skylands Spring",
    "Skylands Summer",
    "Skylands Winter",
    "Snowy Badlands",
    "Snowy Maple Forest",
    "Snowy Shield",
    "Steppe",
    "Stony Spires",
    "Temperate Highlands",
    "Tropical Jungle",
    "Valley Clearing",
    "Volcanic Crater",
    "Volcanic Peaks",
    "Warm River",
    "Warped Mesa",
    "White Cliffs",
    "White Mesa",
    "Windswept Spires",
    "Wintry Forest",
    "Wintry Lowlands",
    "Yellowstone",
    "Yosemite Cliffs",
    "Yosemite Lowlands"
];

function getRandomBiome() {
    var paragraph = document.getElementsByClassName("result")[0];
    var biomes = vanillaBiomes.concat(terralithBiomes);
    var result = biomes[Math.floor(Math.random() * biomes.length)];
    paragraph.innerText = result;
}

